# Generated by Django 6.0.1 on 2026-01-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='is_embedded',
            field=models.BooleanField(default=False, help_text='Embedding generated or not'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='embedding_id',
            field=models.CharField(blank=True, help_text='Vector DB reference ID', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Extracted plain text from resume'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='job_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On-Site'), ('hybrid', 'Hybrid')], default='on-site', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='vector_id',
            field=models.CharField(help_text='Vector store ID (FAISS/Chroma/Pinecone)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parsed_skills',
            field=models.JSONField(blank=True, default=list, help_text='Normalized skills list'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vector_summary',
            field=models.TextField(blank=True, help_text='Structured summary used for embeddings'),
        ),
    ]
