# Generated by Django 6.0.1 on 2026-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_internship_is_embedded_userprofile_embedding_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='is_embedded',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='embedding_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_text',
        ),
        migrations.AddField(
            model_name='internship',
            name='skills_required',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills'),
        ),
    ]
